server:
  port: 8030
spring:
  application:
    name: gatewayserver
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true





eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
